apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:25:01Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1594"
  uid: e73db23e-db94-4952-90c7-f35dd8b49678
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.71.138
  clusterIPs:
  - 10.110.71.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32222
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
